# Generated by Django 2.2.1 on 2023-04-20 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название технологии')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='Описание технологии')),
                ('mastered', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Степень освоения')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название курса')),
                ('school', models.CharField(max_length=512, verbose_name='Название школы')),
                ('year', models.CharField(max_length=512, verbose_name='Время обучения')),
                ('certificate', models.ImageField(blank=True, upload_to='training/', verbose_name='Диплом')),
            ],
        ),
    ]
