# Generated by Django 2.2.1 on 2023-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskil',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color'),
        ),
    ]
