# Generated by Django 2.2.1 on 2023-04-24 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20230424_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=512, verbose_name='Должность')),
                ('company', models.CharField(max_length=512, verbose_name='Компания')),
                ('duties', models.CharField(max_length=1024, verbose_name='Должностные обязанности')),
                ('achievements', models.CharField(max_length=1024, verbose_name='Должностные обязанности')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало работы')),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Завершение работы')),
            ],
        ),
        migrations.AddField(
            model_name='hardskil',
            name='carriers',
            field=models.ManyToManyField(related_name='carrier', to='about.Carrier', verbose_name='Работа'),
        ),
    ]
