# Generated by Django 2.2.1 on 2023-04-21 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_hardskil_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskil',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
