# Generated by Django 2.2.1 on 2023-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20230421_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-end']},
        ),
        migrations.AddField(
            model_name='hardskil',
            name='course',
            field=models.ManyToManyField(to='about.Training'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Диплом'),
        ),
    ]
