# Generated by Django 2.2.1 on 2023-04-21 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20230421_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskil',
            name='course',
            field=models.ManyToManyField(to='about.Training', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='hardskil',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.CreateModel(
            name='SkillInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Training')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.HardSkil')),
            ],
        ),
    ]
