# Generated by Django 2.2.1 on 2023-04-21 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20230421_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Конец обучения'),
        ),
    ]
